version: "3.1"
services:

  mysql:
    image: mysql:8.1
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=football
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
